# Generated by Django 5.1.15 on 2026-03-11 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0002_initial'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatTipoNombramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombramiento', models.CharField(max_length=60, unique=True)),
                ('origen', models.CharField(choices=[('IPN', 'IPN'), ('CONAHCYT', 'CONAHCyT'), ('EXTERNO', 'Externo')], max_length=10)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'tipo de nombramiento',
                'verbose_name_plural': 'tipos de nombramiento',
                'ordering': ['origen', 'nombramiento'],
            },
        ),
        migrations.CreateModel(
            name='Nombramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(blank=True, max_length=20)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='nombramientos/')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nombramientos', to='nombramientos.cattiponombramiento')),
            ],
            options={
                'verbose_name': 'nombramiento',
                'verbose_name_plural': 'nombramientos',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='NombramientoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombramiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores_nombramiento', to='nombramientos.nombramiento')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombramientos_profesor', to='personas.profesor')),
            ],
            options={
                'verbose_name': 'nombramiento de profesor',
                'verbose_name_plural': 'nombramientos de profesores',
                'unique_together': {('profesor', 'nombramiento')},
            },
        ),
        migrations.CreateModel(
            name='ProgramaNombramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombramiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_nombramiento', to='nombramientos.nombramiento')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombramientos_programa', to='programas.programa')),
            ],
            options={
                'verbose_name': 'nombramiento de programa',
                'verbose_name_plural': 'nombramientos de programas',
                'unique_together': {('programa', 'nombramiento')},
            },
        ),
    ]
