# Generated by Django 5.1.15 on 2026-03-25 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombramientos', '0001_initial'),
        ('personas', '0003_alter_estudiante_options_profesor_departamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cattiponombramiento',
            options={'ordering': ['nombramiento'], 'verbose_name': 'tipo de nombramiento', 'verbose_name_plural': 'tipos de nombramiento'},
        ),
        migrations.AlterModelOptions(
            name='nombramiento',
            options={'ordering': ['-fecha_inicio', '-fecha_emision'], 'verbose_name': 'nombramiento', 'verbose_name_plural': 'nombramientos'},
        ),
        migrations.AddField(
            model_name='nombramiento',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nombramiento',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nombramiento',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombramientos', to='personas.profesor'),
        ),
        migrations.AlterField(
            model_name='cattiponombramiento',
            name='nombramiento',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cattiponombramiento',
            name='origen',
            field=models.CharField(blank=True, choices=[('IPN', 'IPN'), ('CONAHCYT', 'CONAHCyT'), ('EXTERNO', 'Externo')], default='IPN', max_length=10),
        ),
        migrations.AlterField(
            model_name='nombramiento',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nombramiento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
