# Generated by Django 5.1.15 on 2026-03-11 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComiteTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comite_tutorial', to='personas.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comites_tutoriales', to='personas.profesor')),
            ],
            options={
                'verbose_name': 'comité tutorial',
                'verbose_name_plural': 'comités tutoriales',
                'unique_together': {('estudiante', 'profesor')},
            },
        ),
        migrations.CreateModel(
            name='DirectorTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('es_codirector', models.BooleanField(default=False)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_recibidas', to='personas.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_tesis', to='personas.profesor')),
            ],
            options={
                'verbose_name': 'director de tesis',
                'verbose_name_plural': 'directores de tesis',
                'unique_together': {('estudiante', 'profesor')},
            },
        ),
        migrations.CreateModel(
            name='JuradoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_examen', models.CharField(choices=[('GRADO', 'Examen de grado'), ('PREDOCTORAL', 'Examen predoctoral')], max_length=15)),
                ('rol', models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('SECRETARIO', 'Secretario'), ('VOCAL', 'Vocal'), ('SUPLENTE', 'Suplente')], max_length=15)),
                ('fecha_examen', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('NO_APROBADO', 'No aprobado')], default='PENDIENTE', max_length=15)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurados', to='personas.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_jurado', to='personas.profesor')),
            ],
            options={
                'verbose_name': 'jurado de examen',
                'verbose_name_plural': 'jurados de examen',
                'unique_together': {('estudiante', 'profesor', 'tipo_examen')},
            },
        ),
    ]
