# Generated by Django 5.1.15 on 2026-03-25 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_estudiante_options_profesor_departamento_and_more'),
        ('programas', '0002_programa_duracion_maxima_meses_alter_programa_nivel'),
        ('tesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comitetutorial',
            options={'verbose_name': 'comite tutorial', 'verbose_name_plural': 'comites tutoriales'},
        ),
        migrations.AddField(
            model_name='comitetutorial',
            name='rol',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='directortesis',
            name='tipo_direccion',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('CODIRECTOR', 'Codirector')], default='DIRECTOR', max_length=15),
        ),
        migrations.AlterField(
            model_name='comitetutorial',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comite_tutorial', to='personas.estudiante'),
        ),
        migrations.AlterField(
            model_name='directortesis',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_recibidas', to='personas.estudiante'),
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('resumen', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('CONCLUIDA', 'Concluida'), ('TITULADA', 'Titulada')], default='EN_PROCESO', max_length=15)),
                ('fecha_registro', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesis', to='personas.estudiante')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tesis', to='programas.programa')),
            ],
            options={
                'verbose_name': 'tesis',
                'verbose_name_plural': 'tesis',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='comitetutorial',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='directortesis',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comitetutorial',
            name='tesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comite_tutorial', to='tesis.tesis'),
        ),
        migrations.AddField(
            model_name='directortesis',
            name='tesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directores', to='tesis.tesis'),
        ),
        migrations.AlterUniqueTogether(
            name='comitetutorial',
            unique_together={('tesis', 'profesor')},
        ),
        migrations.AlterUniqueTogether(
            name='directortesis',
            unique_together={('tesis', 'profesor')},
        ),
    ]
