# Generated by Django 5.1.15 on 2026-03-11 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=10, unique=True)),
                ('nivel', models.CharField(choices=[('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado'), ('ESPECIALIDAD', 'Especialidad')], max_length=15)),
                ('url_doc_base', models.URLField(blank=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'programa',
                'verbose_name_plural': 'programas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=20, unique=True)),
                ('jefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratorios_dirigidos', to='personas.profesor')),
            ],
            options={
                'verbose_name': 'laboratorio',
                'verbose_name_plural': 'laboratorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinaciones', to='personas.profesor')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinadores', to='programas.programa')),
            ],
            options={
                'verbose_name': 'coordinador',
                'verbose_name_plural': 'coordinadores',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
