# Generated by Django 5.1.15 on 2026-03-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='duracion_maxima_meses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nivel',
            field=models.CharField(choices=[('ESPECIALIDAD', 'Especialidad'), ('MAESTRIA', 'Maestria'), ('DOCTORADO', 'Doctorado'), ('DOCTORADO_DIRECTO', 'Doctorado Directo')], max_length=20),
        ),
    ]
