# Generated by Django 5.1.15 on 2026-03-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('generacion', models.IntegerField()),
                ('modalidad', models.CharField(choices=[('TC', 'Tiempo completo'), ('TP', 'Tiempo parcial')], default='TC', max_length=2)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EGRESADO', 'Egresado'), ('BAJA_TEMPORAL', 'Baja temporal'), ('BAJA_DEFINITIVA', 'Baja definitiva'), ('GRADUADO', 'Graduado')], default='ACTIVO', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paterno', models.CharField(max_length=45)),
                ('materno', models.CharField(blank=True, max_length=45)),
                ('nombres', models.CharField(max_length=45)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('cvu', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('NE', 'No especificado')], max_length=2)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personas/fotos/')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['paterno', 'materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('grado_academico', models.CharField(choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20)),
                ('fecha_ingreso_ipn', models.DateField(blank=True, null=True)),
                ('fecha_ingreso_cic', models.DateField(blank=True, null=True)),
                ('es_externo', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': 'profesores',
                'ordering': ['persona__paterno'],
            },
        ),
    ]
