# Generated by Django 5.1.15 on 2026-03-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['matricula'], 'verbose_name': 'alumno', 'verbose_name_plural': 'alumnos'},
        ),
        migrations.AddField(
            model_name='profesor',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profesor',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='orcid',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='ORCID'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='grado_academico',
            field=models.CharField(choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestria'), ('DOCTORADO', 'Doctorado')], max_length=20),
        ),
    ]
